-- AlterEnum
BEGIN;
CREATE TYPE "ActivityType_new" AS ENUM ('CREATED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'ASSIGNED', 'UNASSIGNED', 'TITLE_CHANGED', 'DESCRIPTION_CHANGED', 'LABEL_ADDED', 'LABEL_REMOVED', 'DUE_DATE_CHANGED', 'COMMENTED', 'FORWARDED', 'MERGED', 'TYPE_CHANGED', 'REPORTER_CHANGED', 'PROJECT_CHANGED', 'TEAM_CHANGED', 'COMMENT_DELETED', 'COMMENT_EDITED', 'ATTACHMENT_REMOVED', 'STEP_ADDED', 'STEP_REMOVED', 'STEP_DONE', 'STEP_REOPENED', 'PLAN_APPLIED', 'REFERENCED');
ALTER TABLE "Activity" ALTER COLUMN "type" TYPE "ActivityType_new" USING ("type"::text::"ActivityType_new");
ALTER TYPE "ActivityType" RENAME TO "ActivityType_old";
ALTER TYPE "ActivityType_new" RENAME TO "ActivityType";
DROP TYPE "public"."ActivityType_old";
COMMIT;
