// Round 12 — the same portal, contrast by fill instead of by line. Generated by make12.mjs from gen.mjs; usage: node gen12.mjs <outDir>
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { FONT, I, ring, avatar, AV, AV_NAME, logo } from "../shared.mjs";
import { CSS, TOKENS } from "./css12.mjs";

const out = process.argv[2] ?? "build";
mkdirSync(out, { recursive: true });

/* ------------------------------------------------------------------ icons */
const X = {
  ...I,
  home: '<path d="M2.5 7.5 8 3l5.5 4.5V13h-4V9.5h-3V13h-4z"/>',
  book: '<path d="M2.5 3.5h4a2 2 0 0 1 1.5.8 2 2 0 0 1 1.5-.8h4v9h-4a1.5 1.5 0 0 0-1.5.8 1.5 1.5 0 0 0-1.5-.8h-4z"/><path d="M8 4.3v8.5"/>',
  stamp: '<path d="M6 8.5V5.5a2 2 0 1 1 4 0v3h2.5v3h-9v-3z"/><path d="M4 13.5h8"/>',
  arrow: '<path d="M3 8h10M9 4l4 4-4 4"/>',
  globe: '<circle cx="8" cy="8" r="5.5"/><path d="M2.5 8h11M8 2.5c2 2 2 9 0 11M8 2.5c-2 2-2 9 0 11"/>',
  info: '<circle cx="8" cy="8" r="5.5"/><path d="M8 7.2v3.5M8 5.2v.1"/>',
  warn: '<path d="M8 2.5 14 13H2z"/><path d="M8 6.5v3M8 11.2v.1"/>',
  thumb: '<path d="M5 7.5v6H2.5v-6z"/><path d="M5 7.5 7.5 3a1.6 1.6 0 0 1 2.4 1.3V7h2.6a1.3 1.3 0 0 1 1.3 1.5l-.8 4a1.3 1.3 0 0 1-1.3 1H5"/>',
  thumbd: '<path d="M11 8.5v-6h2.5v6z"/><path d="M11 8.5 8.5 13a1.6 1.6 0 0 1-2.4-1.3V9H3.5a1.3 1.3 0 0 1-1.3-1.5l.8-4a1.3 1.3 0 0 1 1.3-1H11"/>',
  clip: '<path d="m11.5 7.5-4.6 4.6a2.5 2.5 0 0 1-3.5-3.5l5.3-5.3a1.7 1.7 0 0 1 2.4 2.4L6 10.8a.8.8 0 0 1-1.2-1.2l4.2-4.2"/>',
  door: '<rect x="3.5" y="2.5" width="9" height="11" rx="1"/><path d="M9.5 8v.1M3.5 13.5h9"/>',
  monitor: '<rect x="2" y="3" width="12" height="8" rx="1.2"/><path d="M6 13.5h4M8 11v2.5"/>',
  drive: '<rect x="2.5" y="4.5" width="11" height="3.5" rx="1"/><rect x="2.5" y="8.5" width="11" height="3.5" rx="1"/><path d="M11 6.2v.1M11 10.2v.1"/>',
  bug: '<path d="M5.5 6.5a2.5 2.5 0 0 1 5 0v4a2.5 2.5 0 0 1-5 0z"/><path d="M2.5 8.5h3M10.5 8.5h3M3.5 4.5l2 2M12.5 4.5l-2 2M3.5 12.5l2-1.5M12.5 12.5l-2-1.5"/>',
  wifi: '<path d="M2 6.5a9 9 0 0 1 12 0M4.2 9a5.8 5.8 0 0 1 7.6 0M6.4 11.3a2.6 2.6 0 0 1 3.2 0"/><path d="M8 13.4v.1"/>',
  ban: '<circle cx="8" cy="8" r="5.5"/><path d="m4.2 4.2 7.6 7.6"/>',
  x: '<path d="M4 4l8 8M12 4l-8 8"/>',
  backl: '<path d="M13 8H3M7 4 3 8l4 4"/>',
};
const ic = (n, cls = "", s = 16) => `<svg class="i ${cls}" viewBox="0 0 16 16" style="width:${s}px;height:${s}px">${X[n]}</svg>`;

/* ------------------------------------------------------------------- data */
const ME = { k: "SL", name: "Sanne Lin", first: "Sanne", email: "sanne.lin@example.org" };

const CATS = [
  { n: "Hardware", i: "laptop", c: "#6366f1", d: "Laptops, monitors, phones and the bits between", cnt: 9, slug: "hardware" },
  { n: "Software & licences", i: "key", c: "#0ea5e9", d: "Applications, licences and updates", cnt: 12, slug: "software" },
  { n: "Access & accounts", i: "lock", c: "#10b981", d: "Passwords, MFA, shared drives and groups", cnt: 8, slug: "access" },
  { n: "Network & Wi-Fi", i: "wifi", c: "#f97316", d: "VPN, office Wi-Fi and guest access", cnt: 5, slug: "network" },
  { n: "Email & calendar", i: "mail", c: "#febe2e", d: "Mailboxes, forwarding, rooms and invites", cnt: 7, slug: "email" },
  { n: "Office & facilities", i: "building", c: "#f43f5e", d: "Badges, desks, printers and meeting rooms", cnt: 6, slug: "office" },
];

const FORMS = [
  { n: "New or replacement laptop", s: "A standard model within a week, or a specific one if your role needs it.", i: "laptop", c: "#6366f1", cat: "Hardware" },
  { n: "Software licence", s: "Figma, Adobe, JetBrains and anything else on the approved list.", i: "key", c: "#0ea5e9", cat: "Software & licences" },
  { n: "Access to a shared drive", s: "Read or edit rights on a team drive or SharePoint site.", i: "drive", c: "#10b981", cat: "Access & accounts" },
  { n: "Report something broken", s: "Anything that stopped working — tell us what and where.", i: "bug", c: "#f43f5e", cat: "Office & facilities" },
  { n: "Guest Wi-Fi for a visitor", s: "A day pass for someone visiting the office.", i: "wifi", c: "#f97316", cat: "Network & Wi-Fi" },
  { n: "Second monitor", s: "For your desk in the office or at home.", i: "monitor", c: "#6366f1", cat: "Hardware" },
];

const ARTICLES = [
  { n: "VPN keeps dropping — what to try first", s: "Three things that fix nine out of ten disconnects before you call us.", cat: "Network & Wi-Fi", min: 2, views: 412 },
  { n: "Set up email on your phone", s: "Outlook on iPhone and Android, with the MFA step people miss.", cat: "Email & calendar", min: 3, views: 388 },
  { n: "Reset your password without calling us", s: "The self-service page, and what to do when it will not accept the code.", cat: "Access & accounts", min: 1, views: 301 },
  { n: "Book a meeting room from Teams", s: "Rooms show up as attendees. Here is where to find them.", cat: "Office & facilities", min: 2, views: 260 },
  { n: "Printing from your laptop", s: "Add the floor printer once; it follows you between floors.", cat: "Office & facilities", min: 2, views: 190 },
  { n: "Sharing files with people outside the company", s: "When a link is fine and when it needs a guest account.", cat: "Access & accounts", min: 3, views: 154 },
];

const MINE = [
  { r: "INC-2609 0119", t: "Laptop will not wake from sleep after Monday's patch", s: "waiting", a: "MK", who: "Sanne", age: "6h", form: "Report something broken", replies: 3, last: "Mila asked you something 2h ago", you: true, p: "high", heat: 0.55 },
  { r: "QST-2609 0122", t: "How do I get a second monitor for the Rotterdam desk?", s: "new", a: null, age: "12m", form: "Second monitor", replies: 0, last: "", p: "medium", heat: 0.05 },
  { r: "INC-2609 0111", t: "Teams call quality poor in the small meeting rooms", s: "progress", a: "MK", age: "5h", form: null, replies: 1, last: "Mila replied 3h ago", p: "medium", heat: 0.28 },
  { r: "CHG-2609 0004", t: "Roll out MFA to the remaining 38 contractors", s: "progress", a: "RD", age: "2d", form: null, replies: 9, last: "Rami replied yesterday", p: "medium", heat: 0.3 },
];
const SETTLED = [
  { r: "QST-2609 0108", t: "Request access to the HR SharePoint site", s: "resolved", a: "MK", age: "6d", form: "Access to a shared drive", replies: 1, last: "Mila replied 6d ago", p: "low" },
  { r: "QST-2609 0112", t: "Onboarding checklist for the two September starters", s: "resolved", a: "TP", age: "2d", form: null, replies: 3, last: "Tomás replied 2d ago", p: "low" },
];

/* ------------------------------------------------------------- pieces */
const tile = (i, c, size = 42, r = 999, s = 19) =>
  `<span class="tile" style="width:${size}px;height:${size}px;border-radius:${r}px;background:${c};color:#fff">${ic(i, "", s)}</span>`;
const refx = (r) => `<span class="ref ${r.slice(0, 3).toLowerCase()}"><b>${r.slice(0, 3)}</b>${r.slice(3)}</span>`;
const stname = { new: "New", progress: "In progress", waiting: "Waiting on you", resolved: "Resolved" };
const st = (s) => `<span class="st">${ring(s)}${stname[s]}</span>`;
const stpill = (s) => {
  const c = { new: "var(--brand)", progress: "var(--p-medium)", waiting: "var(--text-3)", resolved: "var(--positive)" }[s];
  return `<span class="pill" style="background:color-mix(in oklab,${c} 14%,transparent);color:${c}">${ring(s)}${stname[s]}</span>`;
};

function strip(kind, html) {
  const icon = { info: "info", warn: "warn", outage: "warn", approve: "stamp" }[kind];
  return `<div class="band ${kind}"><div class="wrap">${ic(icon, "", 16)}${html}</div></div>`;
}
const ANNOUNCE = strip("info", `<b>Planned maintenance on the file servers</b><span>Saturday 20 September, 08:00–12:00 — shared drives will be read-only.</span><span class="until mono">Until 20 Sep 12:00</span>`);
const APPROVE = strip("approve", `<span><b>Something has been waiting 2 days on your approval</b> · <span class="mono" style="font-size:12.5px">CHG-2609 0004</span> Roll out MFA to the remaining 38 contractors</span><a class="act">Answer it ${ic("arrow", "", 13)}</a>`);

function top(active, { staff = true, menu = false } = {}) {
  const item = (k, label, n = 0) => `<a class="${active === k ? "on" : ""}">${label}${n ? `<span class="n">${n}</span>` : ""}</a>`;
  const userMenu = menu
    ? `<div class="menu">
        <div class="me">${avatar(ME.k, 32)}<div><b>${ME.name}</b><span>${ME.email}</span></div></div>
        <div class="lbl">Theme</div>
        <div class="theme"><span>${ic("sun", "", 13)}Light</span><span class="on">${ic("moon", "", 13)}Dark</span><span>System</span></div>
        <div class="mi">${ic("logout", "t3", 15)}Sign out</div>
      </div>`
    : "";
  return `
  <div class="top"><div class="wrap" style="position:relative">
    <span class="lockup">${logo(26)}Service portal</span>
    <nav class="nav">${item("home", "Home")}${item("answers", "Answers")}${item("requests", "My requests", 4)}${item("approvals", "Approvals", 1)}</nav>
    <div class="right">
      <span class="ibtn" title="Search">${ic("search", "", 18)}</span>
      ${staff ? `<span class="vsep"></span><span class="switch">${ic("panel", "", 14)}Service desk</span>` : ""}
      <span class="vsep"></span>
      ${avatar(ME.k, 32)}
    </div>
    ${userMenu}
  </div></div>`;
}

const FOOT = `<div class="footer"><div class="wrap"><span>Service portal</span><span>·</span><a>Service desk</a><span style="margin-left:auto" class="mono">Tiqo</span></div></div>`;

function field() {
  // The signal field, drawn once as spans so it is decoration and nothing else.
  const N = 40, W = 620, H = 260, target = 0.62;
  const cols = ["urgent", "high", "medium", "low"];
  let s = "";
  for (let i = 0; i < N; i++) {
    const t = i / (N - 1);
    const wave = 0.3 + 0.28 * Math.sin(t * 6.1 + 0.8) + 0.18 * Math.sin(t * 13.7 + 2.1) + 0.1 * Math.sin(t * 27 + 0.3);
    const h = Math.max(0.05, Math.min(0.95, wave));
    const amber = (i * 7) % 11 !== 0;
    const c = amber ? "var(--brand)" : `var(--p-${cols[(i * 5) % 4]})`;
    const hot = h > target;
    s += `<i style="left:${(i * (W / N)).toFixed(1)}px;width:${(W / N - 6).toFixed(1)}px;height:${(h * H).toFixed(0)}px;background:${c};opacity:${hot ? 0.95 : (0.18 + h * 0.35).toFixed(2)};${hot ? `box-shadow:0 0 14px 1px ${c}` : ""}"></i>`;
  }
  return `<div class="field">${s}<span style="position:absolute;left:0;right:0;bottom:${(target * H).toFixed(0)}px;border-top:1px dashed rgba(255,255,255,.22)"></span></div>`;
}

function hero({ search = false } = {}) {
  const dd = search
    ? `<div class="dd" style="top:66px">
        ${[["monitor", "#6366f1", "Second monitor", "Request · Hardware · For your desk in the office or at home.", true], ["laptop", "#6366f1", "New or replacement laptop", "Request · Hardware · A standard model within a week."], ["book", "#8e8e99", "Two screens on a MacBook — which adapter", "Answer · Hardware · The dock and cable combinations that work."], ["book", "#8e8e99", "Printing from your laptop", "Answer · Office & facilities · Add the floor printer once."]]
          .map(([i, c, n, s, on]) => `<div class="hit ${on ? "on" : ""}">${tile(i, c, 34, 999, 16)}<div style="min-width:0"><div class="n">${n}</div><div class="s">${s}</div></div>${on ? `<kbd style="margin-left:auto">↵</kbd>` : ""}</div>`)
          .join("")}
        <div class="foot">See all results for “monitor” ${ic("arrow", "", 13)}</div>
      </div>`
    : "";
  return `
  <div class="hero"><div class="wrap">
    <div class="deco"><div class="glow"></div></div>
    <div class="float">
      <div class="fc a"><div class="h">${ring("progress")}Laptop will not wake from sleep</div><div class="s">Mila is on it · replied 3h ago</div><div class="bar"><i></i></div></div>
      <div class="fc b"><div class="h"><span class="ok">${ic("check", "", 17)}</span>Resolved</div><div class="s">Access to the HR SharePoint site</div></div>
      <div class="fc c"><div class="h">${avatar("MK", 24)}Mila Kuipers</div><div class="s">“Could you try it on battery once and tell me whether it wakes?”</div></div>
    </div>
    <div class="copy">
      <h1>Good morning, ${ME.first}.</h1>
      <p class="welcome">What do you need? Search for an answer, or ask us for something.</p>
      <div style="position:relative">
        <div class="search">${ic("search", "", 19)}<span class="ph">${search ? `<span style="color:#0b0b0d">monitor</span>` : "Search answers and requests"}</span><kbd>⌘K</kbd><span class="go">${ic("arrow", "", 18)}</span></div>
        ${dd}
      </div>
      <div class="starts">${CATS.slice(0, 4).map((c) => `<span>${ic(c.i, "", 14)}${c.n}</span>`).join("")}</div>
      <div class="desk"><span class="dot"></span><b>The desk is open</b> until 17:30 · usually answered in about 4 hours</div>
    </div>
  </div></div>`;
}

const shelf = () => `
  <div class="shelf">${CATS.slice(0, 5).map((c, i) => `<a class="${i === 2 ? "hover" : ""}">${tile(c.i, c.c, 56, 999, 24)}<span class="name">${c.n}</span><span class="cnt">${c.cnt} items</span></a>`).join("")}<a class="all"><span class="tile" style="width:56px;height:56px;border-radius:999px;background:var(--surface-2);color:var(--text);box-shadow:inset 0 0 0 1.5px var(--line-strong)">${ic("arrow", "", 22)}</span><span class="name">Browse everything</span><span class="cnt">47 items · 7 sections</span></a></div>`;

const svc = (f, hover = false) => `
  <a class="card svc ${hover ? "hover" : ""}">${tile(f.i, f.c)}<span class="n">${f.n}</span><span class="s">${f.s}</span><span class="m">${f.cat}<span class="arr">${ic("arrow", "", 14)}</span></span></a>`;

const reqRow = (m) => `
  <a class="req">${ring(m.s)}<div style="min-width:0;flex:1"><div class="t">${m.t}</div><div class="sub" style="display:flex;align-items:center;gap:8px">${refx(m.r)} · ${m.age} ago${m.you ? `<span class="tag you">Waiting for your reply</span>` : ""}</div></div></a>`;

const waiting = () => `
  <a class="waiting"><span class="ico">${ic("msg", "", 17)}</span><span><b style="font-weight:600">Mila is waiting for your answer</b> on <span class="ref">INC-2609 0119</span> · Laptop will not wake from sleep after Monday's patch</span><span class="since">waiting 2h for your reply</span><span class="go">Reply ${ic("arrow", "", 13)}</span></a>`;

const deskcard = () => `
  <div class="card deskcard">
    <div class="cardhead">The service desk</div>
    <div class="row"><span class="ico" style="background:color-mix(in oklab,var(--positive) 14%,transparent);color:var(--positive)">${ic("clock", "", 16)}</span><div><div class="l">Opening hours</div><div style="font-weight:500">Open until 17:30 · Mon–Fri 08:30–17:30</div></div></div>
    <div class="row"><span class="ico">${ic("reply", "", 16)}</span><div><div class="l">Usually answered in</div><div style="font-weight:500">About 4 hours</div></div></div>
    <div class="row"><span class="ico">${ic("phone", "", 16)}</span><div><div class="l">Urgent and the desk is closed</div><div style="font-weight:500">+31 30 123 4567</div></div></div>
  </div>`;

/* ------------------------------------------------------------- screens */
function home({ search = false, menu = false } = {}) {
  return `
  <div class="portal">
    ${top("home", { menu })}
    ${ANNOUNCE}
    ${hero({ search })}
    <div class="wrap">
      ${shelf()}
      <div class="content">
        ${waiting()}
        <div>
          <div class="sec">
            <div class="sechead"><h2>Common requests</h2><span class="sub">The things people ask for most</span><a class="more">Everything ${ic("arrow", "", 13)}</a></div>
            <div class="services">${FORMS.map((f, i) => svc(f, i === 0)).join("")}</div>
          </div>
          <div class="sec">
            <div class="sechead"><h2>Answers</h2><span class="sub">Solve it yourself, in a minute, without waiting for us</span><a class="more">All answers ${ic("arrow", "", 13)}</a></div>
            <div class="card answers">${ARTICLES.slice(0, 4).map((a, i) => `<a class="${i === 1 ? "hover" : ""}"><span class="bk">${ic("book", "", 15)}</span><span style="min-width:0"><span class="n">${a.n}</span><span class="s">${a.s}</span><span class="c">${a.cat} · ${a.min} min read</span></span></a>`).join("")}</div>
          </div>
        </div>
        <div class="side">
          <div class="card">
            <div class="cardhead">Your requests<a>4 open</a></div>
            ${MINE.map(reqRow).join("")}
            <div class="cardfoot">My requests ${ic("arrow", "", 13)}</div>
          </div>
          ${deskcard()}
        </div>
      </div>
    </div>
    ${FOOT}
  </div>`;
}

function category() {
  const c = CATS[0];
  const forms = FORMS.filter((f) => f.cat === "Hardware").concat([{ n: "Phone or SIM", s: "A work phone, a SIM for your own, or a replacement.", i: "phone", c: "#6366f1", cat: "Hardware" }, { n: "Headset or webcam", s: "For calls from the office or from home.", i: "monitor", c: "#6366f1", cat: "Hardware" }]);
  return `
  <div class="portal">
    ${top("home")}
    <div class="wrap">
      <div class="pagehead">
        <div class="crumbs"><span>Home</span>${ic("chev", "", 12)}<span class="cur">${c.n}</span></div>
        <div class="headrow">
          <div style="display:flex;gap:18px;align-items:center">${tile(c.i, c.c, 56, 16, 26)}<div><h1>${c.n}</h1><p class="blurb">${c.d}.</p></div></div>
          <div class="tools"><div class="input" style="width:320px">${ic("search", "t3", 15)}<span class="ph">Search in ${c.n}</span><kbd>⌘K</kbd></div></div>
        </div>
      </div>
      <div class="sec">
        <div class="sechead"><h2>Requests</h2><span class="sub">${forms.length} in this section</span></div>
        <div class="services" style="grid-template-columns:repeat(4,1fr)">${forms.map((f, i) => svc(f, i === 1)).join("")}</div>
      </div>
      <div class="sec" style="padding-bottom:56px">
        <div class="sechead"><h2>Answers</h2><span class="sub">Read these first — most hardware questions end here</span></div>
        <div class="agrid">${[ARTICLES[0], { n: "Two screens on a MacBook — which adapter", s: "The dock and cable combinations that work, and the one that never does.", cat: "Hardware", min: 2 }, { n: "Battery drains fast after an update", s: "Usually indexing. Here is how to tell, and how long to wait.", cat: "Hardware", min: 1 }].map((a) => `<a class="card acard"><span class="n">${a.n}</span><span class="s">${a.s}</span><span class="m">${ic("book", "", 13)}${a.min} min read</span></a>`).join("")}</div>
      </div>
    </div>
    ${FOOT}
  </div>`;
}

function form() {
  const f = FORMS[5];
  return `
  <div class="portal">
    ${top("home")}
    <div class="wrap">
      <div class="pagehead">
        <div class="crumbs"><span>Home</span>${ic("chev", "", 12)}<span>Hardware</span>${ic("chev", "", 12)}<span class="cur">${f.n}</span></div>
        <div style="display:flex;gap:18px;align-items:center">${tile(f.i, f.c, 56, 16, 26)}<div><h1>${f.n}</h1><p class="blurb">A 27-inch screen for your desk in the office or at home. Standard monitors ship within a week; anything else we will check with you first.</p></div></div>
      </div>
      <div style="display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:40px;padding-bottom:56px">
        <div class="card form">
          <div class="fs">
            <div class="lg">What do you need</div><div class="ld">Two lines is plenty. We will ask if we need more.</div>
            <div class="fields">
              <div class="f full"><span class="fl">Subject<i>*</i></span><span class="fi filled">Second monitor for the Rotterdam desk</span></div>
              <div class="f full">
                <div class="suggest" style="margin:0">
                  <div class="h">${ic("book", "", 15)}This might already answer it<a>None of these</a></div>
                  <div class="it">${ic("book", "t3", 15)}<div><div>Two screens on a MacBook — which adapter</div><div class="s">The dock and cable combinations that work, and the one that never does.</div></div></div>
                  <div class="it">${ic("book", "t3", 15)}<div><div>Home-office equipment — what you can ask for</div><div class="s">Monitor, chair, desk and the budget for each.</div></div></div>
                </div>
              </div>
              <div class="f"><span class="fl">Where is the desk<i>*</i></span><span class="fi sel filled">Rotterdam office ${ic("chevd", "t3", 14)}</span></div>
              <div class="f"><span class="fl">Needed by</span><span class="fi">Pick a date</span><span class="hint">Leave empty if any time next week is fine.</span></div>
              <div class="f full"><span class="fl">Which kind<i>*</i></span>
                <div class="radio"><span class="on"><span class="dot"></span>Standard 27-inch (Dell, USB-C) — in stock</span><span><span class="dot"></span>Something else — I will describe it below</span></div>
              </div>
              <div class="f full"><span class="fl">Anything else</span><span class="fi ta">Model, mount, or why the standard one will not do…</span></div>
            </div>
          </div>
          <div class="fs">
            <div class="lg">Attachments</div><div class="ld">Drop a photo or paste a screenshot into any answer.</div>
            <div style="display:flex;gap:8px;align-items:center"><span class="btn outline sm">${ic("clip", "", 14)}Attach a file</span><span class="attach">${ic("note", "", 13)}desk-photo.jpg<span class="mono">1.2 MB</span>${ic("x", "t3", 12)}</span></div>
          </div>
          <div class="formfoot">
            <div class="lines">Raised as a <b>medium</b> question · answered by <b>Workplace</b> within about 8h<br>Updates go to <b>${ME.email}</b> and to My requests</div>
            <span class="btn primary">${ic("send", "", 16)}Send</span>
          </div>
        </div>
        <div class="side">
          <div class="card"><div class="cardhead">Before you ask</div><div class="rel">${[["Two screens on a MacBook — which adapter", "2 min read"], ["Home-office equipment — what you can ask for", "3 min read"]].map(([n, m]) => `<a>${ic("book", "t3", 15)}<span style="min-width:0"><span style="font-weight:500">${n}</span><span class="s">${m}</span></span></a>`).join("")}</div></div>
          ${deskcard()}
        </div>
      </div>
    </div>
    ${FOOT}
  </div>`;
}

function request() {
  const m = MINE[0];
  return `
  <div class="portal">
    ${top("requests")}
    <div class="wrap">
      <a class="back">${ic("backl", "", 14)}My requests</a>
      <div class="detail">
        <div>
          <div class="callout" style="margin-bottom:22px"><span class="ico">${ic("stamp", "", 17)}</span><div style="flex:1"><div class="h">Your approval is needed</div><div class="s">Replace the laptop rather than repair it? · Whole ticket · due 19 Sep</div></div><div style="display:flex;gap:8px"><span class="btn primary sm">${ic("check", "", 14)}Approve</span><span class="btn outline sm">${ic("x", "", 14)}Refuse</span></div></div>
          <div class="ok" style="margin-bottom:22px"><span class="ico">${ic("check", "", 18)}</span><span><b style="font-weight:600">Your request has been raised.</b> We have it. You can follow it here and reply at any time.</span></div>
          <div style="display:flex;align-items:center;gap:10px"><span class="mono t3" style="font-size:13px">${refx(m.r)}</span>${stpill("waiting")}</div>
          <h1>${m.t}</h1>
          <div class="meta">Raised 16 Sep 09:12 · through <b style="color:var(--text-2);font-weight:500">Report something broken</b></div>

          <div class="card facts" style="margin-top:22px">
            <div><div class="l">Looking after it</div><div class="v">${avatar("MK", 22)}Mila Kuipers</div></div>
            <div><div class="l">Due date</div><div class="v">${ic("cal", "t3", 15)}Thu 18 Sep, 17:30</div></div>
          </div>

          <div class="card" style="margin-top:20px">
            <div class="cardhead">What you asked</div>
            <div class="prose" style="padding:18px">
              <p>Since Monday's patch the laptop will not wake from sleep. Closing the lid and opening it again shows a black screen with the fan on; only a long press on the power button brings it back.</p>
              <p>It happened four times today. Nothing else changed.</p>
              <div style="display:flex;gap:8px;margin-top:14px"><span class="attach">${ic("note", "", 13)}IMG_4412.jpg<span class="mono">2.1 MB</span></span><span class="attach">${ic("note", "", 13)}system-report.txt<span class="mono">14 KB</span></span></div>
            </div>
          </div>

          <div class="card" style="margin-top:20px">
            <div class="cardhead">Related requests</div>
            <div class="rel"><a>${ring("resolved")}<span style="min-width:0"><span class="t3" style="font-size:12px">relates to</span> <span style="font-weight:500">Battery drains fast after the same update</span></span><span style="margin-left:auto" class="t3">Resolved</span></a></div>
          </div>

          <div class="card" style="margin-top:20px">
            <div class="msg desk"><div class="who">${avatar("MK", 24)}<b>Mila Kuipers</b><span class="tag" style="background:var(--surface-3);color:var(--text-2)">Service desk</span><span class="when">16 Sep 10:40</span></div><div class="body">Thanks Sanne — that patch has a known wake bug on this model. Two questions so I can pick the right fix: is the laptop on the dock when it happens, and does it also fail on battery?</div></div>
            <div class="msg"><div class="who">${avatar("SL", 24)}<b>You</b><span class="when">16 Sep 11:05</span></div><div class="body">On the dock every time. I have not tried on battery yet, will do this afternoon.</div></div>
            <div class="msg desk"><div class="who">${avatar("MK", 24)}<b>Mila Kuipers</b><span class="tag" style="background:var(--surface-3);color:var(--text-2)">Service desk</span><span class="when">Today 08:52</span></div><div class="body">Perfect. Could you try it on battery once and tell me whether it wakes? If it does, the dock firmware is the culprit and I can push the update remotely.</div></div>
            <div class="composer" style="border-top:1px solid var(--line)">
              <div class="lbl" style="font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--text-3);margin-bottom:10px">Add a reply</div>
              <div class="area">Anything you want to add…</div>
              <div class="foot"><span class="btn ghost sm">${ic("clip", "", 14)}Attach</span><span class="t3" style="font-size:12px">or drop a file here</span><span class="btn primary sm" style="margin-left:auto">${ic("send", "", 14)}Send</span></div>
            </div>
          </div>
        </div>
        <div class="side" style="padding-top:8px">
          <div class="card">
            <div class="cardhead">Where it stands</div>
            <div style="padding:16px 18px;display:flex;flex-direction:column;gap:14px;font-size:13.5px">
              ${[["resolved", "Raised", "16 Sep 09:12"], ["resolved", "Picked up by Mila", "16 Sep 09:30"], ["waiting", "Waiting for your reply", "since 08:52 today"], ["new", "Resolved", "—"]].map(([s, n, w], i) => `<div style="display:flex;align-items:center;gap:10px;${i === 3 ? "opacity:.45" : ""}">${ring(s)}<span style="font-weight:500">${n}</span><span class="t3 mono" style="margin-left:auto;font-size:12px">${w}</span></div>`).join("")}
            </div>
          </div>
          ${deskcard()}
        </div>
      </div>
    </div>
    ${FOOT}
  </div>`;
}

function requests() {
  const rrow = (m, done = false) => `
    <div class="rrow ${done ? "done" : ""}">
      <span class="spine ${m.heat > 0.5 && !done ? "hot" : ""}" style="--c:var(--p-${m.p})"><i style="height:${Math.round((m.heat ?? 1) * 100)}%"></i></span>
      ${refx(m.r)}
      <div style="min-width:0"><div class="t"><span>${m.t}</span>${m.you ? `<span class="tag you">Waiting for your reply</span>` : ""}</div><div class="meta">${m.form ? `<span>${m.form}</span><span>·</span>` : ""}<span class="mono">${m.age} ago</span>${m.replies ? `<span>·</span><span style="display:inline-flex;align-items:center;gap:4px">${ic("msg", "", 12)}${m.replies} ${m.replies === 1 ? "reply" : "replies"}</span>` : ""}${m.last ? `<span>·</span><span>${m.last}</span>` : ""}</div></div>
      <div class="st">${ring(m.s)}${stname[m.s]}<span class="who">${avatar(m.a, 22)}</span></div>
      ${ic("chev", "t3", 14)}
    </div>`;
  return `
  <div class="portal">
    ${top("requests")}
    ${APPROVE}
    <div class="wrap">
      <div class="pagehead">
        <div class="headrow">
          <div><h1>My requests</h1><p class="blurb">Everything you have asked us for, and where it stands.</p></div>
          <div class="tools">
            <span class="seg"><span class="on">All <span class="k">6</span></span><span>Open <span class="k">4</span></span><span>Settled <span class="k">2</span></span></span>
            <div class="input" style="width:260px">${ic("search", "t3", 15)}<span class="ph">Search your requests</span></div>
            <span class="btn brand">${ic("plus", "", 15)}Make a request</span>
          </div>
        </div>
      </div>
      ${waiting()}
      <div class="grouphead">Still open<span class="k">4</span></div>
      <div class="card" style="padding-left:18px">${MINE.map((m) => rrow(m)).join("")}</div>
      <div class="grouphead">Settled<span class="k">2</span></div>
      <div class="card" style="padding-left:18px;margin-bottom:56px">${SETTLED.map((m) => rrow({ ...m, heat: 1 }, true)).join("")}</div>
    </div>
    ${FOOT}
  </div>`;
}

function answers() {
  const groups = [["Network & Wi-Fi", [ARTICLES[0], { n: "Guest Wi-Fi — how visitors get on", s: "The password changes weekly. Here is where reception keeps it.", min: 1 }, { n: "Working from a hotel or train", s: "What the VPN needs, and the captive portals that block it.", min: 2 }]], ["Email & calendar", [ARTICLES[1], { n: "Out-of-office that actually reaches externals", s: "Two settings, both needed.", min: 1 }, { n: "Shared mailbox not showing in Outlook", s: "Add it explicitly once; auto-mapping takes a day.", min: 2 }]], ["Access & accounts", [ARTICLES[2], ARTICLES[5], { n: "MFA on a new phone", s: "Move the authenticator before you wipe the old one.", min: 2 }]]];
  return `
  <div class="portal">
    ${top("answers")}
    <div class="wrap">
      <div class="pagehead">
        <div class="headrow">
          <div><h1>Answers</h1><p class="blurb">Solve it yourself, in a minute, without waiting for us.</p></div>
          <div class="tools"><div class="input" style="width:360px">${ic("search", "t3", 15)}<span class="ph">What do you need? Search for an answer or a request</span></div></div>
        </div>
        <div style="margin-top:22px;display:flex;align-items:center;gap:12px"><span class="label">Often read</span><div class="often">${ARTICLES.slice(0, 4).map((a) => `<span>${a.n}</span>`).join("")}</div></div>
      </div>
      ${groups.map(([g, list]) => `<div class="sec"><div class="sechead"><h2 style="font-size:17px">${g}</h2><span class="sub mono">${list.length}</span></div><div class="agrid">${list.map((a) => `<a class="card acard"><span class="n">${a.n}</span><span class="s">${a.s}</span><span class="m">${ic("book", "", 13)}${a.min} min read</span></a>`).join("")}</div></div>`).join("")}
      <div style="height:16px"></div>
    </div>
    ${FOOT}
  </div>`;
}

function article() {
  const a = ARTICLES[0];
  return `
  <div class="portal">
    ${top("answers")}
    <div class="wrap">
      <div class="pagehead" style="padding-bottom:0">
        <div class="crumbs"><span>Home</span>${ic("chev", "", 12)}<span>Answers</span>${ic("chev", "", 12)}<span class="cur">${a.cat}</span></div>
        <h1 style="max-width:26ch">${a.n}</h1>
        <p class="blurb" style="max-width:70ch">${a.s}</p>
        <div class="byline">${avatar("MK", 20)}by Mila Kuipers<span>·</span>${avatar("JB", 20)}Updated 2 Sep by Jonas Berg<span>·</span>${a.min} min read</div>
      </div>
      <div class="article" style="margin-top:28px">
        <div class="card">
          <div class="prose" style="padding:26px 28px 22px">
            <h2 style="margin-top:0">1. Turn Wi-Fi off and on, not the VPN</h2>
            <p>Nine out of ten drops are the laptop hopping between two access points that both look equally good. Toggling Wi-Fi forces it to pick one and stay there. Wait ten seconds before you turn it back on.</p>
            <h2>2. Forget the guest network</h2>
            <p>If you have ever joined <code>Office-Guest</code>, your laptop will keep trying it. Remove it from the known networks list; the corporate network is the only one you need.</p>
            <h2>3. Check the client version</h2>
            <p>Anything below <code>4.12</code> drops every twenty minutes on the new Utrecht access points. Open the client, click the gear, and choose <b>Check for updates</b>.</p>
            <ul><li>If it updates and the drops stop, you are done.</li><li>If it says it is up to date and still drops, raise a request below and mention this page.</li></ul>
          </div>
          <div class="feedback">Did this solve it?<span class="vote on">${ic("thumb", "", 14)}Yes</span><span class="vote">${ic("thumbd", "", 14)}Not really</span><span class="tally">Helped 38 people this month</span></div>
        </div>
        <div class="side">
          <div class="card"><div class="cardhead">Related answers</div><div class="rel">${[["Working from a hotel or train", "What the VPN needs, and the captive portals that block it."], ["Guest Wi-Fi — how visitors get on", "The password changes weekly."]].map(([n, s]) => `<a>${ic("book", "t3", 15)}<span style="min-width:0"><span style="font-weight:500">${n}</span><span class="s">${s}</span></span>${ic("chev", "t3", 13)}</a>`).join("")}</div></div>
          <div class="card"><div class="cardhead">Still stuck?</div><div style="padding:14px 18px;font-size:13.5px" class="t2">Raise a request and we will pick it up.</div><div class="rel" style="border-top:1px solid var(--line)">${[FORMS[4], FORMS[3]].map((f) => `<a>${tile(f.i, f.c, 30, 8, 15)}<span style="min-width:0"><span style="font-weight:500">${f.n}</span><span class="s">${f.s}</span></span>${ic("arrow", "t3", 13)}</a>`).join("")}</div></div>
        </div>
      </div>
    </div>
    ${FOOT}
  </div>`;
}

function search() {
  const hits = [
    { kind: "form", ...FORMS[5] }, { kind: "form", ...FORMS[0] },
    { kind: "art", n: "Two screens on a MacBook — which adapter", s: "The dock and cable combinations that work, and the one that never does.", cat: "Hardware" },
    { kind: "art", ...ARTICLES[4] }, { kind: "form", n: "Home-office equipment", s: "Monitor, chair, desk and the budget for each.", i: "building", c: "#f43f5e", cat: "Office & facilities" },
  ];
  return `
  <div class="portal">
    ${top("home")}
    <div class="wrap">
      <div class="pagehead">
        <div class="headrow">
          <div><h1>5 results</h1><p class="blurb">for “monitor”</p></div>
          <div class="tools"><div class="input" style="width:420px;border-color:var(--brand);box-shadow:0 0 0 3px var(--brand-tint)">${ic("search", "t3", 15)}<span class="ph" style="color:var(--text)">monitor</span><span class="t3" style="display:flex">${ic("x", "", 13)}</span></div></div>
        </div>
      </div>
      <div class="sec">
        <div class="sechead"><h2 style="font-size:17px">Requests</h2><span class="sub mono">3</span></div>
        <div class="services">${hits.filter((h) => h.kind === "form").map((f) => svc(f)).join("")}</div>
      </div>
      <div class="sec" style="padding-bottom:56px">
        <div class="sechead"><h2 style="font-size:17px">Answers</h2><span class="sub mono">2</span></div>
        <div class="agrid">${hits.filter((h) => h.kind === "art").map((a) => `<a class="card acard"><span class="n">${a.n}</span><span class="s">${a.s}</span><span class="m">${ic("book", "", 13)}In ${a.cat}</span></a>`).join("")}</div>
      </div>
    </div>
    ${FOOT}
  </div>`;
}

function approvals() {
  return `
  <div class="portal">
    ${top("approvals")}
    <div class="wrap">
      <div class="pagehead"><h1>Approvals</h1><p class="blurb">The desk has asked you to say yes or no before this work goes ahead.</p></div>
      <div style="display:grid;grid-template-columns:minmax(0,1fr) 380px;gap:40px;padding-bottom:56px">
        <div>
          <div class="card" style="border-color:color-mix(in oklab,var(--brand) 40%,transparent)">
            <div style="padding:18px 22px;display:flex;gap:14px;align-items:flex-start">
              <span class="ico" style="width:36px;height:36px;border-radius:10px;background:var(--brand);color:var(--brand-ink);display:flex;align-items:center;justify-content:center;flex:none">${ic("stamp", "", 17)}</span>
              <div style="flex:1;min-width:0">
                <div class="mono t3" style="font-size:12px">About CHG-2609 0004</div>
                <div style="font-weight:600;font-size:17px;letter-spacing:-.015em;margin-top:2px">Roll out MFA to the remaining 38 contractors</div>
                <div class="t3" style="font-size:13px;margin-top:4px">Gates the <b style="color:var(--text-2);font-weight:500">Rollout</b> phase · asked by Rami Daoud · <b style="color:var(--negative);font-weight:600">overdue</b> since 15 Sep</div>
              </div>
            </div>
            <div style="margin:0 22px;padding:14px 16px;border-radius:12px;background:var(--surface-2);border:1px solid var(--line)"><div class="label" style="margin-bottom:8px">What was asked for</div><div class="prose" style="font-size:13.5px"><p>Every contractor account gets MFA enforced on Monday 22 September. They receive the enrolment mail on Thursday; anyone who has not enrolled by Monday is locked out until they do.</p><p>Your team has 11 of the 38.</p></div></div>
            <div style="padding:16px 22px;font-size:14px">Are your 11 contractors ready for the lock-out on Monday?</div>
            <div style="padding:0 22px 20px;display:flex;gap:8px"><span class="btn primary">${ic("check", "", 15)}Approve</span><span class="btn outline">${ic("x", "", 15)}Refuse</span><span class="t3" style="margin-left:auto;font-size:12.5px;align-self:center">Refusing asks for a reason</span></div>
          </div>
          <div class="grouphead" style="margin-top:32px">What you have already answered</div>
          <div class="card">${[["CHG-2609 0002", "Move the intranet to the new hosting account", true, ""], ["CHG-2609 0001", "Replace the badge readers on floor 3", false, "Not before the audit, please."]].map(([r, t, yes, c]) => `<div style="display:flex;align-items:center;gap:14px;padding:12px 18px;border-bottom:1px solid var(--line);font-size:13.5px"><span class="mono t3" style="font-size:12px">${r}</span><span style="min-width:0;flex:1"><span style="font-weight:500;display:block">${t}</span>${c ? `<span class="t3" style="font-size:12.5px">“${c}”</span>` : ""}</span><span style="display:inline-flex;align-items:center;gap:5px;color:${yes ? "var(--positive)" : "var(--negative)"};font-weight:600">${ic(yes ? "check" : "x", "", 14)}${yes ? "Yes" : "No"}</span></div>`).join("")}</div>
        </div>
        <div class="side">
          <div class="card"><div class="cardhead">Why you are asked</div><div style="padding:14px 18px;font-size:13.5px;line-height:1.55" class="t2">The desk only asks when the work touches something you own. Your answer is recorded on the request, with your name and the time.</div></div>
          ${deskcard()}
        </div>
      </div>
    </div>
    ${FOOT}
  </div>`;
}

function closed() {
  return `
  <div class="portal" style="height:900px">
    <div class="top"><div class="wrap"><span class="lockup">${logo(26)}Service portal</span></div></div>
    <div class="closed">
      <span class="tile">${ic("door", "", 28)}</span>
      <h1>The portal is closed</h1>
      <p>We are moving the file servers this weekend. The portal is back on Monday 22 September at 08:30 — for anything urgent, call +31 30 123 4567.</p>
      <span class="btn outline" style="margin-top:8px">${ic("panel", "", 15)}Service desk</span>
    </div>
    ${FOOT}
  </div>`;
}

/* -------------------------------------------------------------- output */
const SCREENS = [
  ["Home", "Portal12Home", 1560, () => home(), "Contrast by fill: grey ground, white cards with a low shadow and no border. The bar sits on the ground with the active section as a white pill. The maintenance notice is a solid band under the bar, one colour per tone (blue information, amber warning, red outage). The hero is the brand colour as a field, ink on it, with three cards from the product floating on the right in place of an illustration. Six sections on the shelf, solid colour, the sixth is Browse everything."],
  ["Home · search and menu", "Portal12HomeSearch", 1000, () => home({ search: true, menu: true }), "The live search and the user menu in the new layer."],
  ["Request form", "Portal12Form", 1340, () => form(), "The form on the same rules: fields as filled wells instead of outlined boxes, the suggestion panel on the brand wash, the ink Send."],
  ["My requests", "Portal12Requests", 1040, () => requests(), "The approval nudge as an amber band under the bar; filters as a pill segment with the active one in ink; the waiting nudge as a card with an amber edge; rows on one white card."],
];

const doc = (theme, body, h) => `<!doctype html>
<html><head><meta charset="utf-8">${FONT}<style>:root{${TOKENS[theme]}} html,body{height:${h}px;overflow:hidden} ${CSS}</style></head><body>${body}</body></html>`;

const boards = [];
for (const [title, file, h, fn, note] of SCREENS) {
  const body = fn();
  for (const theme of ["dark", "light"]) {
    const name = `${file}${theme === "light" ? "Light" : ""}.dc.html`;
    writeFileSync(join(out, name), doc(theme, body, h));
    boards.push({ file: name, title: `${title} · ${theme}`, h, theme, screen: title, note });
  }
}

/* the viewer: one page, every screen, dark/light toggle */
const viewer = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Tiqo Portal · Round 12</title>${FONT}
<style>
:root{--bg:#fff;--surface:#fff;--surface-2:#f4f4f5;--line:rgba(9,9,11,.08);--text:#09090b;--text-2:#52525b;--text-3:#9d9da6;--brand:#febe2e;--seg-on:#fff}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#09090b;--surface:#121214;--surface-2:#18181b;--line:rgba(255,255,255,.08);--text:#fafafa;--text-2:#a1a1aa;--text-3:#6b6b74;--seg-on:#232326}}
:root[data-theme="dark"]{--bg:#09090b;--surface:#121214;--surface-2:#18181b;--line:rgba(255,255,255,.08);--text:#fafafa;--text-2:#a1a1aa;--text-3:#6b6b74;--seg-on:#232326}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Geist,system-ui,sans-serif;font-size:14px;line-height:1.5;-webkit-font-smoothing:antialiased}
.wrap{max-width:1360px;margin:0 auto;padding:28px 24px 80px}
.head{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;flex-wrap:wrap;position:sticky;top:0;background:var(--bg);padding:16px 0 14px;z-index:9;border-bottom:1px solid var(--line)}
.head h1{font-size:22px;font-weight:600;letter-spacing:-.02em;margin:0}.head p{margin:4px 0 0;color:var(--text-2);max-width:80ch}
.seg{display:inline-flex;background:var(--surface-2);border:1px solid var(--line);border-radius:8px;padding:2px;gap:2px}
.seg button{border:0;background:transparent;color:var(--text-2);font:inherit;font-size:13px;font-weight:500;height:28px;padding:0 12px;border-radius:6px;cursor:pointer}
.seg button[aria-pressed="true"]{background:var(--seg-on);color:var(--text);box-shadow:0 1px 2px rgba(9,9,11,.12)}
.brief{margin:24px 0 8px;padding:18px 20px;border:1px solid var(--line);border-radius:12px;background:var(--surface);color:var(--text-2);max-width:none;line-height:1.6}
.brief b{color:var(--text)}
.toc{display:flex;flex-wrap:wrap;gap:6px;margin:16px 0 0}.toc a{font-size:12.5px;color:var(--text-2);border:1px solid var(--line);border-radius:999px;padding:4px 10px;text-decoration:none}.toc a:hover{color:var(--text)}
.screen{margin-top:44px;padding-top:22px;border-top:1px solid var(--line)}
.screen h2{font-size:17px;font-weight:600;letter-spacing:-.015em;margin:0}.screen .note{margin:4px 0 14px;color:var(--text-2);max-width:90ch}
.stage{position:relative;width:100%;overflow:hidden;border:1px solid var(--line);border-radius:12px;background:var(--surface)}
.stage iframe{position:absolute;left:0;top:0;width:1440px;border:0;transform-origin:0 0;display:none}
.stage iframe.show{display:block}
</style></head><body><div class="wrap">
<div class="head"><div><h1>Tiqo Portal · Round 12</h1><p>The round-11 portal with a new visual layer, and the desk queue with one rule from it. Both themes; toggle here.</p></div>
<div class="seg" role="group"><button data-t="dark" aria-pressed="true">Dark</button><button data-t="light" aria-pressed="false">Light</button></div></div>
<div class="brief"><b>What changed.</b> Round 11 separated everything with 1px lines and gave every card the same weight; this round separates by fill instead. The page ground is a soft grey, cards are white with a low shadow and no border, and the dark theme mirrors it. The hero is the brand colour as a large field rather than ink, so the tenant's colour finally appears somewhere big. Category colour is used solid on round tiles instead of a 14% tint on a square. The type scale opens up: 46px greeting, 24px section titles, 36px page titles. The content column is 1320px on a 1440 screen.<br><br><b>Your three points.</b> The maintenance notice now sits under the bar as a solid band per tone, not above it. The shelf keeps six across; the sixth slot is always Browse everything, so 5, 6 or 7 sections never leave a ragged row and an admin picks which five lead. Width is up from 1200 to 1320.<br><br><b>The desk.</b> The last board is today's queue with only the fill rule applied — rail and bar on the ground, the work area as one white panel — so we can judge whether the app should follow.
<div class="toc">${SCREENS.map(([t, f]) => `<a href="#${f}">${t}</a>`).join("")}<a href="#Queue12">Desk queue · fill rule</a></div></div>
${SCREENS.map(([title, file, h, , note]) => `<section class="screen" id="${file}"><h2>${title}</h2><p class="note">${note}</p><div class="stage" data-h="${h}"><iframe data-t="dark" class="show" src="./${file}.dc.html" style="height:${h}px" loading="lazy"></iframe><iframe data-t="light" src="./${file}Light.dc.html" style="height:${h}px" loading="lazy"></iframe></div></section>`).join("")}
<section class="screen" id="Queue12"><h2>Desk queue · the fill rule only</h2><p class="note">Today's queue board, untouched except for one rule: rail and bar sit on the grey ground with no lines, the work area is one white panel with a low shadow, row dividers drop to a faint line. Nothing else moved.</p><div class="stage" data-h="900"><iframe data-t="dark" class="show" src="./Queue12.dc.html" style="height:900px" loading="lazy"></iframe><iframe data-t="light" src="./Queue12Light.dc.html" style="height:900px" loading="lazy"></iframe></div></section>
</div>
<script>
(function(){
  function fit(){document.querySelectorAll('.stage').forEach(function(st){var s=st.clientWidth/1440;st.style.height=Math.round(st.dataset.h*s)+'px';st.querySelectorAll('iframe').forEach(function(f){f.style.transform='scale('+s+')'})})}
  addEventListener('resize',fit);fit();
  var segs=document.querySelectorAll('.seg button[data-t]');
  segs.forEach(function(b){b.addEventListener('click',function(){segs.forEach(function(x){x.setAttribute('aria-pressed',x===b?'true':'false')});document.documentElement.dataset.theme=b.dataset.t;document.querySelectorAll('.stage iframe').forEach(function(f){f.classList.toggle('show',f.dataset.t===b.dataset.t)})})});
})();
</script></body></html>`;
writeFileSync(join(out, "PortalRound12.html"), viewer);
writeFileSync(join(out, "portal12-boards.json"), JSON.stringify(boards, null, 2));
console.log(`${boards.length} boards + viewer → ${out}`);
