// Builds gen12.mjs from gen.mjs (a patched copy) and the two queue boards with the fill rule.
// Run from design/mockups: node src/portal/make12.mjs && node src/portal/gen12.mjs boards
import { readFileSync, writeFileSync } from "node:fs";
let s = readFileSync("src/portal/gen.mjs", "utf8");
const fn = (name, body) => {
  const re = s.includes(`function ${name}(`)
    ? new RegExp(`function ${name}\\([^)]*\\) \\{[\\s\\S]*?\\n\\}\\n`)
    : new RegExp(`const ${name} = \\([^)]*\\) =>[\\s\\S]*?>\`;\\n`);
  if (!re.test(s)) throw new Error("no fn " + name);
  s = s.replace(re, body.trim() + "\n");
};
s = s.replace(/^\/\/ Round 11[\s\S]*?import \{ THEMES, FONT, I, ring, avatar, AV, AV_NAME, logo \} from "\.\.\/shared\.mjs";/, `// Round 12 — the same portal, contrast by fill instead of by line. Generated by make12.mjs from gen.mjs; usage: node gen12.mjs <outDir>
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { FONT, I, ring, avatar, AV, AV_NAME, logo } from "../shared.mjs";
import { CSS, TOKENS } from "./css12.mjs";`);
s = s.replace(/\/\* -+ tokens \*\/[\s\S]*?\n`;\n\n\/\* -+ data \*\//, "/* ------------------------------------------------------------------- data */");
s = s.replace(/const tile = [\s\S]*?<\/span>`;\n/,"const tile = (i, c, size = 42, r = 999, s = 19) =>\n  `<span class=\"tile\" style=\"width:${size}px;height:${size}px;border-radius:${r}px;background:${c};color:#fff\">${ic(i, \"\", s)}</span>`;\n");
fn("strip", `function strip(kind, html) {
  const icon = { info: "info", warn: "warn", outage: "warn", approve: "stamp" }[kind];
  return \`<div class="band \${kind}"><div class="wrap">\${ic(icon, "", 16)}\${html}</div></div>\`;
}`);
fn("hero", `function hero({ search = false } = {}) {
  const dd = search
    ? \`<div class="dd" style="top:66px">
        \${[["monitor", "#6366f1", "Second monitor", "Request · Hardware · For your desk in the office or at home.", true], ["laptop", "#6366f1", "New or replacement laptop", "Request · Hardware · A standard model within a week."], ["book", "#8e8e99", "Two screens on a MacBook — which adapter", "Answer · Hardware · The dock and cable combinations that work."], ["book", "#8e8e99", "Printing from your laptop", "Answer · Office & facilities · Add the floor printer once."]]
          .map(([i, c, n, s, on]) => \`<div class="hit \${on ? "on" : ""}">\${tile(i, c, 34, 999, 16)}<div style="min-width:0"><div class="n">\${n}</div><div class="s">\${s}</div></div>\${on ? \`<kbd style="margin-left:auto">↵</kbd>\` : ""}</div>\`)
          .join("")}
        <div class="foot">See all results for “monitor” \${ic("arrow", "", 13)}</div>
      </div>\`
    : "";
  return \`
  <div class="hero"><div class="wrap">
    <div class="deco"><div class="glow"></div></div>
    <div class="float">
      <div class="fc a"><div class="h">\${ring("progress")}Laptop will not wake from sleep</div><div class="s">Mila is on it · replied 3h ago</div><div class="bar"><i></i></div></div>
      <div class="fc b"><div class="h"><span class="ok">\${ic("check", "", 17)}</span>Resolved</div><div class="s">Access to the HR SharePoint site</div></div>
      <div class="fc c"><div class="h">\${avatar("MK", 24)}Mila Kuipers</div><div class="s">“Could you try it on battery once and tell me whether it wakes?”</div></div>
    </div>
    <div class="copy">
      <h1>Good morning, \${ME.first}.</h1>
      <p class="welcome">What do you need? Search for an answer, or ask us for something.</p>
      <div style="position:relative">
        <div class="search">\${ic("search", "", 19)}<span class="ph">\${search ? \`<span style="color:#0b0b0d">monitor</span>\` : "Search answers and requests"}</span><kbd>⌘K</kbd><span class="go">\${ic("arrow", "", 18)}</span></div>
        \${dd}
      </div>
      <div class="starts">\${CATS.slice(0, 4).map((c) => \`<span>\${ic(c.i, "", 14)}\${c.n}</span>\`).join("")}</div>
      <div class="desk"><span class="dot"></span><b>The desk is open</b> until 17:30 · usually answered in about 4 hours</div>
    </div>
  </div></div>\`;
}`);
fn("shelf", `const shelf = () => \`
  <div class="shelf">\${CATS.slice(0, 5).map((c, i) => \`<a class="\${i === 2 ? "hover" : ""}">\${tile(c.i, c.c, 56, 999, 24)}<span class="name">\${c.n}</span><span class="cnt">\${c.cnt} items</span></a>\`).join("")}<a class="all"><span class="tile" style="width:56px;height:56px;border-radius:999px;background:var(--surface-2);color:var(--text);box-shadow:inset 0 0 0 1.5px var(--line-strong)">\${ic("arrow", "", 22)}</span><span class="name">Browse everything</span><span class="cnt">47 items · 7 sections</span></a></div>\`;`);
const R = (a, b) => { if (!s.includes(a)) throw new Error("miss " + a.slice(0, 40)); s = s.replace(a, b); };
R('${ANNOUNCE}\n    ${top("home", { menu })}\n    ${hero({ search })}', '${top("home", { menu })}\n    ${ANNOUNCE}\n    ${hero({ search })}');
R('${ARTICLES.slice(0, 4).map((a) => `<a>', '${ARTICLES.slice(0, 4).map((a, i) => `<a class="${i === 1 ? "hover" : ""}">');
R('${APPROVE}\n    ${top("requests")}', '${top("requests")}\n    ${APPROVE}');
R('<span class="btn primary">${ic("plus", "", 15)}Make a request</span>', '<span class="btn brand">${ic("plus", "", 15)}Make a request</span>');
s = s.replace(/const SCREENS = \[[\s\S]*?\n\];\n/, `const SCREENS = [
  ["Home", "Portal12Home", 1560, () => home(), "Contrast by fill: grey ground, white cards with a low shadow and no border. The bar sits on the ground with the active section as a white pill. The maintenance notice is a solid band under the bar, one colour per tone (blue information, amber warning, red outage). The hero is the brand colour as a field, ink on it, with three cards from the product floating on the right in place of an illustration. Six sections on the shelf, solid colour, the sixth is Browse everything."],
  ["Home · search and menu", "Portal12HomeSearch", 1000, () => home({ search: true, menu: true }), "The live search and the user menu in the new layer."],
  ["Request form", "Portal12Form", 1340, () => form(), "The form on the same rules: fields as filled wells instead of outlined boxes, the suggestion panel on the brand wash, the ink Send."],
  ["My requests", "Portal12Requests", 1040, () => requests(), "The approval nudge as an amber band under the bar; filters as a pill segment with the active one in ink; the waiting nudge as a card with an amber edge; rows on one white card."],
];
`);
s = s.replace(/const doc = [\s\S]*?<\/html>`;\n/, "const doc = (theme, body, h) => `<!doctype html>\n<html><head><meta charset=\"utf-8\">${FONT}<style>:root{${TOKENS[theme]}} html,body{height:${h}px;overflow:hidden} ${CSS}</style></head><body>${body}</body></html>`;\n");
R("<title>Tiqo Portal · Round 11</title>", "<title>Tiqo Portal · Round 12</title>");
R("<h1>Tiqo Portal · Round 11</h1><p>The requester portal, redrawn from a blank page. Every screen in both themes; toggle here.</p>", "<h1>Tiqo Portal · Round 12</h1><p>The round-11 portal with a new visual layer, and the desk queue with one rule from it. Both themes; toggle here.</p>");
s = s.replace(/<div class="brief">[\s\S]*?<div class="toc">/, `<div class="brief"><b>What changed.</b> Round 11 separated everything with 1px lines and gave every card the same weight; this round separates by fill instead. The page ground is a soft grey, cards are white with a low shadow and no border, and the dark theme mirrors it. The hero is the brand colour as a large field rather than ink, so the tenant's colour finally appears somewhere big. Category colour is used solid on round tiles instead of a 14% tint on a square. The type scale opens up: 46px greeting, 24px section titles, 36px page titles. The content column is 1320px on a 1440 screen.<br><br><b>Your three points.</b> The maintenance notice now sits under the bar as a solid band per tone, not above it. The shelf keeps six across; the sixth slot is always Browse everything, so 5, 6 or 7 sections never leave a ragged row and an admin picks which five lead. Width is up from 1200 to 1320.<br><br><b>The desk.</b> The last board is today's queue with only the fill rule applied — rail and bar on the ground, the work area as one white panel — so we can judge whether the app should follow.
<div class="toc">`);
R('${SCREENS.map(([t, f]) => `<a href="#${f}">${t}</a>`).join("")}</div></div>', '${SCREENS.map(([t, f]) => `<a href="#${f}">${t}</a>`).join("")}<a href="#Queue12">Desk queue · fill rule</a></div></div>');
R("</div>\n<script>", `<section class="screen" id="Queue12"><h2>Desk queue · the fill rule only</h2><p class="note">Today's queue board, untouched except for one rule: rail and bar sit on the grey ground with no lines, the work area is one white panel with a low shadow, row dividers drop to a faint line. Nothing else moved.</p><div class="stage" data-h="900"><iframe data-t="dark" class="show" src="./Queue12.dc.html" style="height:900px" loading="lazy"></iframe><iframe data-t="light" src="./Queue12Light.dc.html" style="height:900px" loading="lazy"></iframe></div></section>\n</div>\n<script>`);
R('"PortalRound11.html"', '"PortalRound12.html"');
R('"portal11-boards.json"', '"portal12-boards.json"');
writeFileSync("src/portal/gen12.mjs", s);

for (const [src, dst] of [["Queue.dc.html", "Queue12.dc.html"], ["QueueLight.dc.html", "Queue12Light.dc.html"]]) {
  let q = readFileSync("boards/" + src, "utf8");
  const L = src.includes("Light");
  const extra = `
    :root { --bg:${L ? "#f1f1f4" : "#0a0a0c"}; --chrome:${L ? "#f1f1f4" : "#0a0a0c"}; --surface:${L ? "#ffffff" : "#151519"}; --surface-2:${L ? "#f4f4f6" : "#1d1d23"}; --line:${L ? "rgba(9,9,11,.06)" : "rgba(255,255,255,.06)"}; --hl:none; --panel:${L ? "0 1px 2px rgba(9,9,11,.04), 0 10px 30px -14px rgba(9,9,11,.14)" : "0 1px 0 rgba(255,255,255,.04) inset, 0 12px 30px -16px rgba(0,0,0,.7)"}; }
    .shell { background: var(--bg); }
    .rail { border-right: 0; background: var(--bg); }
    .bar { border-bottom: 0; background: var(--bg); }
    .main { margin: 0 12px 12px 0; border-radius: 14px; background: var(--surface); box-shadow: var(--panel); overflow: hidden; }
    .rail .nav a.on { background: var(--surface); box-shadow: var(--panel); }
    .card { border: 0; box-shadow: var(--panel); }
    .input, .btn.outline { border-color: transparent; box-shadow: var(--panel); }
  </style>`;
  q = q.replace("</style>", extra).replace("background:var(--bg);position:sticky", "background:var(--surface-2);position:sticky");
  writeFileSync("boards/" + dst, q);
}
console.log("gen12.mjs + queue boards written");
